---
- name: Import networks.yml
  ansible.builtin.import_tasks: networks.yml
  vars:
    ansible_python_interpreter: "{{ os_networks_venv }}/bin/python"
  environment:
    OS_IDENTITY_API_VERSION: "3"
